# Pytorch

- Open source library for deep learning applications.
- Originated from Torch Library. 
- 2 essential features:
    1. **Tensor Computing**: Similar to NumPy arrays, Pytorch provides **Tensors**, which are generalizations of matrices and serves as basic building blocks of Deep Learning Algorithms. 
    2. **Automatic Differentiation**: In Deep Learning, we need to adjust parameters (**gradients**). 

## Pytorch ecosystem

1. **Torchvision**: Datasets, models and transforms for computer vision.
2. **Torchtext**: NLP. Dataloaders, vocabularies and common text transformations --> Simplify preprocessing pipeline for text-based applications.
3. **Torchaudio**: Dataset, model architectures and audio transformations.
4. **ONNX Integration**: Ensures interoperability between AI frameworks --> Allow users to transition their models to other platforms.
5. **Captum**: Offer model interpretability and understanding tools for deep learning.
6. **Ecosystem tools**: Albumentations (image augmentations, lighting), etc.

## Basic Elements:

1. **Tensors**: Fundamental data structure. 
2. **Computational Graph**: Define and modify the graph on the go.
3. **Autograd module**: Automatic differentiation for all operations on tensors (useful in backpropagation). 
4. **Neural Network Module**: Design and train neural network. 
    - Pre defined layers.
    - Loss functions.
    - Optimizations routines.
5. **Optim module**: Optimization routines, gradient descent variations. 
6. **Utilities**: Data handling to performance profiling 

# Main modules

In [ ]:
from pytorch import nn #neural network
from pytorch import optim #optimization
from pytorch import autograd # automatic differentiation
from pytorch import torchvision # computer vision

# Data Loader

- **Batch processing**: Automates mini-batch creation for frequent model weight updates.
- **Shuffling**: Ordenar al azar
- **Parallel Loading** Usa subprocesos multiples para cargar la data, optimizando el uso del CPU.
- **Custom Data Handling**: Permite utilizar datasets propios.

In [4]:
import torch
from torch.utils.data import DataLoader, Dataset

# Define a custom dataset class
class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data
    
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index]
    
# Create a sample dataset
data = [1, 2, 3, 4, 5]
dataset = CustomDataset(data)

# Create a data loader
batch_size = 2
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Iterate over the data loader
for batch in dataloader:
    print(batch)


tensor([4, 2])
tensor([1, 5])
tensor([3])


# Use cases:

1. Computer vision
2. NLP
3. Generative models 
4. Reinforcement learning
5. Audio Processing
6. Health care
7. Autonomous Vehicules
8. Finance
9. Sistemas de recomendación
10. Dispositivos perifericos

# Beneficios

1. Acelera la productividad de los desarrolladores.
2. Fácil de aprender y sencillo de codificar
3. Simplificadad y transparencia
4. Fácil de debuggear
5. Paralelismo de data

# Pytorch vs Tensorflow: Cuando Pytorch gana

1. Pytorch ofrece **dynamic computation graph** en comparación de la versión estático de Tensorflow. Esto consiste en definir mientras se ejecuta el modelo. 
2. Debug: Usa herramientas nativas de Pyhon para solucionar problemas.
3. Research Friendliness: Mezclar modelos, probar nuevas arquitecturas, experimentar sin mucho problema.